### PR TITLE
Improve mouse events when hovering player and pip player

### PR DESCRIPTION
**Pull request by bragaru-i**
- Fixes: https://github.com/Collaborne/backlog/issues/1236
- some small refactor (related to multi usage of the useMediaStore)

### CODE REVIEW

**Review by IdrissMahjoubi — APPROVED** [review]
LGTM (please check lint warning)

**Review by sudhons — APPROVED** [review]
LGTM

**Review by koyewonqw — CHANGES_REQUESTED** [review]
Hi Ivan,
When the controls disappear, the "progress bar(=progress slider)" needs to be remain at the bottom(stick to bottom). could you pls correct this? besides that, every thing looks great, thanks!

**Review by koyewonqw — APPROVED** [review]
LGTM

**Pull request merged**
