### PR TITLE
Add UI for the audio files also with audio only `*.mp4` file (AudioPlayer)

### PR DESCRIPTION
**Pull request by bragaru-i**
- Fixes: https://github.com/Collaborne/backlog/issues/1223

### CODE REVIEW

**Review by ronnyroeller — CHANGES_REQUESTED** [review]
The placeholder `audio-placeholder.svg` is NEXT-specific. Considering that this is an open source project: could we use a generic placeholder that can be overwritten by the user?

**Review by ronnyroeller — CHANGES_REQUESTED** [review]
`static/audio-placeholder.svg` seems to be still NEXT specific image... Could you replace it with a generic image?

**Comment by bragaru-i** [comment]
@ronnyroeller, maybe leaving a black screen?
do not have a generic one atm

**Comment by ronnyroeller** [comment]
> @ronnyroeller, maybe leaving a black screen? do not have a generic one atm

Sure - works as well

**Comment by koyewonqw** [comment]
LGTM

**Review by ronnyroeller — APPROVED** [review]
LGTM

**Pull request merged**
