### PR TITLE
Add badges for Readme.md

### PR DESCRIPTION
**Pull request by bragaru-i**
Add following badges:
- documentation coverage (using typedoc plugin)
- node vesion
- workflow status

### CODE REVIEW

**Review by ronnyroeller — APPROVED** [review]
LGTM

**Review by ronnyroeller — CHANGES_REQUESTED** [review]
This seems to add not just badges but also change documentation. Is this on purpose?

**Comment by bragaru-i** [comment]
> This seems to add not just badges but also change documentation. Is this on purpose?

Documentation is build on every PR (typedoc builds them on each PR automatically).

**Comment by ronnyroeller** [comment]
> We should add some extra functionality to run docs only if in the PR we have triggered a component implied in docs renewal

Even then, this needs to a separate PR - otherwise it's impossible to review documentation changes.

**Review by ronnyroeller — APPROVED** [review]
LGTM

**Pull request merged**
